### ISSUE TITLE
Decide on a coding style

### ISSUE THREAD

**Issue by tech-no-crat** [ic-cubesat/cube-gui#3]
We need to decide on a coding style to use and stick with it. I suggest we use the [Google JavaScript Style](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml).

**Comment by paul-g** [comment]
The [Mozilla Coding Style](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style) looks fine. Should we go for this?

**Comment by tech-no-crat** [comment]
Mozilla it is.
